// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDOaRzRlh039z5ee0kYUQFvjWZ8eOnS4Ng',
    appId: '1:516822111404:android:843fb8c41dd0a36de43b09',
    messagingSenderId: '516822111404',
    projectId: 'pizza-7fbfd',
    storageBucket: 'pizza-7fbfd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxzQlV_bF6c7gQEpMzFxtIxoUx8-zEpEM',
    appId: '1:516822111404:ios:55c00d93b67bc32be43b09',
    messagingSenderId: '516822111404',
    projectId: 'pizza-7fbfd',
    storageBucket: 'pizza-7fbfd.appspot.com',
    iosBundleId: 'com.example.pizzadelivery',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDwqeNPKZru3RmWgsr4d_iHYCfCu0OPxd4',
    appId: '1:516822111404:web:625f2332b9bbaa05e43b09',
    messagingSenderId: '516822111404',
    projectId: 'pizza-7fbfd',
    authDomain: 'pizza-7fbfd.firebaseapp.com',
    storageBucket: 'pizza-7fbfd.appspot.com',
    measurementId: 'G-4B849Q45DS',
  );
}
